# Generated by Django 5.0.6 on 2024-08-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0006_saler_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saler_reg',
            name='date',
        ),
    ]
