# Generated by Django 5.0.6 on 2024-07-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_cart_size_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_details',
        ),
    ]
