# Generated by Django 5.0.6 on 2024-07-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
